### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
There is no need for a 2DS Pokemon edition listing. It's the same thing.

### CODE REVIEW

**Comment by dukesrg** [comment]
AFAIK 2DS could have a different NAND size depending on a package.

**Comment by ghost** [comment]
N3DS and O3DS also have different NAND sizes.. Why not add every single bundle then?

**Comment by ghost** [comment]
Also its random. Not based on bundles. Toshiba and Samsung nands are different for every 3ds model. i.e N3DS 1.2GB NAND and N3DS 1.9GB NAND.

**Comment by dukesrg** [comment]
@iAqua 
In that case we need to check both too, since now NAND partitions is detected directly from NCSD MBR record with no predefined values and actual chip detection. If it will be reported to support any type/size - then there should be no differences even between 2DS and 3DS.

**Comment by dukesrg** [comment]
Added N3DS flash variants 0865daa488748c11753a6bf7168172e208a8518b

**Pull request closed without merging**
